version: '3.8'

services:
  postgres:
    image: postgres:15-alpine3.18
    container_name: product_api_postgres
    environment:
      POSTGRES_DB: product_api_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:6.21
    container_name: product_api_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_network
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
    name: product_api_postgres_data
  pgadmin_data:
    name: product_api_pgadmin_data