version: '3.8'

services:
  postgres:
    image: postgres:15-alpine3.18
    container_name: product_api_postgres
    environment:
      POSTGRES_DB: product_api_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:6.21
    container_name: product_api_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_network
    depends_on:
      - postgres
    restart: unless-stopped

  redis:
    image: reg-hk.agodadev.io/dockerhub/redis:7.4.2
    container_name: product_api_redis
    command: ["redis-server", "--appendonly", "yes"] # Enables persistence
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - redis_network
    restart: unless-stopped

  redisinsight:
    image: reg-hk.agodadev.io/dockerhub/redislabs/redisinsight:1.14.0
    container_name: product_api_redisinsight
    environment:
      - REDISINSIGHT_AUTH_ENABLED=false # Disable authentication for simplicity
    ports:
      - "8002:8001"
    networks:
      - redis_network
    depends_on:
      - redis
    restart: unless-stopped

networks:
  postgres_network:
    driver: bridge
  redis_network:
    driver: bridge

volumes:
  postgres_data:
    name: product_api_postgres_data
  pgadmin_data:
    name: product_api_pgadmin_data
  redis_data:
    name: product_api_redis_data
